// Khớp NotificationResponses / NotificationType của Backend

export type NotificationType =
  | "BOOKING_PAID"
  | "BOOKING_CANCELLED"
  | "REFUND_COMPLETED"
  | "TRIP_REMINDER"
  | "REVIEW_INVITE"
  | "REVIEW_REPLIED"
  | "REVIEW_HIDDEN"
  | "REVIEW_UNHIDDEN"
  | "NEW_REVIEW"
  | "TOUR_REVIEW_HIDDEN"
  | "TOUR_REVIEW_UNHIDDEN"
  | "CUSTOM_REQUEST_ACCEPTED"
  | "CUSTOM_REQUEST_CLOSED"
  | "CUSTOM_REQUEST_ASSIGNED"
  | "CUSTOM_REQUEST_EXPIRED"
  | "CUSTOM_REQUEST_CANCELLED"
  | "CUSTOM_REQUEST_NEW"
  | "CUSTOM_REQUEST_DECLINED"
  | "CUSTOM_REQUEST_REASSIGNING"
  | "CUSTOM_PROPOSAL_RECEIVED"
  | "CUSTOM_PROPOSAL_EXPIRING"
  | "CUSTOM_PROPOSAL_EXPIRED"
  | "CUSTOM_PROPOSAL_REVISION_REQUESTED"
  | "CUSTOM_PROPOSAL_ACCEPTED"
  | "CUSTOM_PROPOSAL_DUE_SOON"
  | "CUSTOM_PROPOSAL_OVERDUE"
  | "CHAT_MESSAGE"
  | "BOOKING_DEPOSIT_PAID"
  | "BOOKING_PAYMENT_DUE"
  | "BOOKING_BALANCE_EXTENDED"
  | "SETTLEMENT_CREATED"
  | "SETTLEMENT_RESOLVED"
  | "SETTLEMENT_PAID"
  | "SETTLEMENT_DISPUTED"
  | "SETTLEMENT_READY"
  | "NEW_BOOKING"
  | "TOUR_APPROVED"
  | "TOUR_NEEDS_REVISION"
  | "TOUR_SUSPENDED"
  | "TOUR_UNSUSPENDED"
  | "AGENT_PROFILE_APPROVED"
  | "AGENT_PROFILE_NEEDS_REVISION"
  | "CHANGE_REQUEST_APPROVED"
  | "CHANGE_REQUEST_REJECTED"
  | "DEPARTURE_REMINDER"
  | "LOW_BOOKINGS"
  | "AGENT_PROFILE_SUBMITTED"
  | "CHANGE_REQUEST_SUBMITTED"
  | "TOUR_SUBMITTED"
  | "MANUAL_REFUND_NEEDED";

export interface NotificationItem {
  id: number;
  type: NotificationType;
  title: string;
  body: string | null;
  link: string | null;
  read: boolean;
  createdAt: string;
}

/** nextCursor = null khi đã hết */
export interface NotificationPage {
  items: NotificationItem[];
  nextCursor: number | null;
}
