-- =====================================================================
-- V10: Đặt tour + thanh toán VNPay + hoàn tiền
--  - bookings: một đơn đặt cho một lịch khởi hành. Giá, tỷ lệ hoa hồng và chính sách hoàn tiền được
--    CHỤP LẠI tại thời điểm đặt (đổi giá / đổi chính sách về sau không ảnh hưởng đơn cũ).
--  - Đơn mới ở trạng thái PENDING_PAYMENT, giữ chỗ tới hold_expires_at (15 phút); quá hạn chưa trả -> tự hủy.
--  - payments: mỗi lần chuyển sang VNPay là một giao dịch (txn_ref duy nhất) — khách có thể thanh toán lại.
--  - refunds: mỗi lần hoàn tiền (tự động qua API VNPay; lỗi thì Admin hoàn thủ công).
--  - Tiền tính bằng VNĐ (số nguyên).
-- =====================================================================

CREATE TABLE bookings (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                     varchar(20)   NOT NULL,
    customer_id              bigint        NOT NULL REFERENCES users (id),
    tour_id                  bigint        NOT NULL REFERENCES tours (id),
    departure_id             bigint        NOT NULL REFERENCES tour_departures (id),
    -- Agent tổ chức tour lúc đặt (NULL = tour của TripConnect)
    agent_id                 bigint REFERENCES users (id),
    status                   varchar(20)   NOT NULL,
    adults                   smallint      NOT NULL,
    children                 smallint      NOT NULL,
    infants                  smallint      NOT NULL,
    adult_price              bigint        NOT NULL,
    child_price              bigint        NOT NULL,
    total_amount             bigint        NOT NULL,
    commission_rate          numeric(5, 4) NOT NULL,
    commission_amount        bigint        NOT NULL,
    contact_name             varchar(100)  NOT NULL,
    contact_phone            varchar(20)   NOT NULL,
    contact_email            varchar(254)  NOT NULL,
    note                     text,
    -- Chính sách hoàn tiền áp dụng cho đơn này
    refund_full_days         smallint      NOT NULL,
    refund_partial_days      smallint      NOT NULL,
    refund_partial_percent   smallint      NOT NULL,
    hold_expires_at          timestamp(6)  NOT NULL,
    paid_at                  timestamp(6),
    completed_at             timestamp(6),
    cancelled_at             timestamp(6),
    cancelled_by             varchar(20),
    cancel_reason            text,
    refund_amount            bigint        NOT NULL DEFAULT 0,
    refund_status            varchar(20)   NOT NULL DEFAULT 'NONE',
    version                  bigint        NOT NULL DEFAULT 0,
    created_at               timestamp(6)  NOT NULL,
    updated_at               timestamp(6),
    CONSTRAINT uq_bookings_code UNIQUE (code),
    CONSTRAINT bookings_status_check CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT bookings_cancelled_by_check CHECK (cancelled_by IN ('CUSTOMER', 'AGENT', 'ADMIN', 'SYSTEM')),
    CONSTRAINT bookings_refund_status_check CHECK (refund_status IN ('NONE', 'PENDING', 'REFUNDED', 'MANUAL_REQUIRED')),
    CONSTRAINT bookings_counts_check CHECK (adults >= 1 AND children >= 0 AND infants >= 0 AND infants <= adults)
);

CREATE INDEX idx_bookings_customer ON bookings (customer_id, created_at DESC);
CREATE INDEX idx_bookings_agent ON bookings (agent_id, created_at DESC);
CREATE INDEX idx_bookings_tour ON bookings (tour_id);
-- Đếm chỗ đã đặt của lịch khởi hành (đơn còn hiệu lực)
CREATE INDEX idx_bookings_departure_active ON bookings (departure_id, status) WHERE status <> 'CANCELLED';
-- Job tự hủy đơn quá hạn giữ chỗ
CREATE INDEX idx_bookings_pending_hold ON bookings (hold_expires_at) WHERE status = 'PENDING_PAYMENT';

CREATE TABLE booking_passengers (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      bigint       NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
    full_name       varchar(100) NOT NULL,
    date_of_birth   date         NOT NULL,
    type            varchar(10)  NOT NULL,
    passport_number varchar(20),
    CONSTRAINT booking_passengers_type_check CHECK (type IN ('ADULT', 'CHILD', 'INFANT'))
);
CREATE INDEX idx_booking_passengers_booking ON booking_passengers (booking_id);

CREATE TABLE payments (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id         bigint       NOT NULL REFERENCES bookings (id),
    -- Mã giao dịch gửi sang VNPay (vnp_TxnRef) — duy nhất, chặn ghi nhận một giao dịch 2 lần
    txn_ref            varchar(40)  NOT NULL,
    amount             bigint       NOT NULL,
    status             varchar(20)  NOT NULL,
    -- vnp_CreateDate gửi VNPay (yyyyMMddHHmmss) — cần khi tra cứu / hoàn tiền
    vnp_create_date    varchar(14)  NOT NULL,
    vnp_transaction_no varchar(30),
    vnp_response_code  varchar(5),
    bank_code          varchar(20),
    pay_date           varchar(14),
    created_at         timestamp(6) NOT NULL,
    updated_at         timestamp(6),
    CONSTRAINT uq_payments_txn_ref UNIQUE (txn_ref),
    CONSTRAINT payments_status_check CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'EXPIRED'))
);
CREATE INDEX idx_payments_booking ON payments (booking_id);
CREATE INDEX idx_payments_pending ON payments (created_at) WHERE status = 'PENDING';

CREATE TABLE refunds (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      bigint       NOT NULL REFERENCES bookings (id),
    payment_id      bigint       NOT NULL REFERENCES payments (id),
    amount          bigint       NOT NULL,
    status          varchar(20)  NOT NULL,
    reason          text         NOT NULL,
    response_code   varchar(5),
    message         text,
    processed_by    bigint REFERENCES users (id),
    processed_at    timestamp(6),
    created_at      timestamp(6) NOT NULL,
    CONSTRAINT refunds_status_check CHECK (status IN ('PENDING', 'SUCCESS', 'MANUAL_REQUIRED', 'MANUAL_DONE'))
);
CREATE INDEX idx_refunds_booking ON refunds (booking_id);
CREATE INDEX idx_refunds_status ON refunds (status);
