-- =====================================================================
-- V15: Thông báo trên web (chuông trên header)
--  - Mỗi người nhận một dòng; thông báo cho Admin được tạo cho từng Admin (mỗi người tự đánh dấu đã đọc).
--  - link: đường dẫn trong trang web (vd /account/bookings/12), bấm vào thông báo thì mở trang này.
--  - Đã đọc quá 60 ngày thì tự xóa (NotificationCleanupJob).
-- =====================================================================

CREATE TABLE notifications (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       varchar(40)  NOT NULL,
    title      varchar(200) NOT NULL,
    body       text,
    link       varchar(500),
    read_at    timestamp(6),
    created_at timestamp(6) NOT NULL
);

-- Danh sách của một người, mới nhất trước (phân trang con trỏ theo id)
CREATE INDEX idx_notifications_user ON notifications (user_id, id DESC);
-- Đếm / lọc chưa đọc
CREATE INDEX idx_notifications_unread ON notifications (user_id, id DESC) WHERE read_at IS NULL;
-- Job dọn thông báo đã đọc lâu
CREATE INDEX idx_notifications_read_at ON notifications (read_at) WHERE read_at IS NOT NULL;
