-- =====================================================================
-- V16: Đánh giá tour
--  - Mỗi đơn "Hoàn thành" được đánh giá một lần (trong 60 ngày), sửa được trong 7 ngày sau khi gửi.
--  - agent_id: đơn vị tổ chức lúc đặt (NULL = tour của TripConnect) — dùng tính điểm trung bình của Agent.
--  - Admin ẩn đánh giá vi phạm (kèm lý do); đánh giá bị ẩn không tính vào điểm trung bình.
--  - Đơn vị tổ chức trả lời công khai 1 lần (sửa được).
-- =====================================================================

CREATE TABLE reviews (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id    bigint       NOT NULL REFERENCES bookings (id),
    tour_id       bigint       NOT NULL REFERENCES tours (id),
    agent_id      bigint REFERENCES users (id),
    customer_id   bigint       NOT NULL REFERENCES users (id),
    rating        smallint     NOT NULL,
    comment       text         NOT NULL,
    hidden        boolean      NOT NULL DEFAULT false,
    hidden_reason text,
    hidden_at     timestamp(6),
    hidden_by     bigint REFERENCES users (id),
    reply         text,
    replied_at    timestamp(6),
    version       bigint       NOT NULL DEFAULT 0,
    created_at    timestamp(6) NOT NULL,
    updated_at    timestamp(6),
    CONSTRAINT uq_reviews_booking UNIQUE (booking_id),
    CONSTRAINT reviews_rating_check CHECK (rating BETWEEN 1 AND 5)
);

-- Trang tour: đánh giá đang hiện, mới nhất trước (phân trang con trỏ theo id)
CREATE INDEX idx_reviews_tour_visible ON reviews (tour_id, id DESC) WHERE hidden = false;
CREATE INDEX idx_reviews_agent ON reviews (agent_id, id DESC);

CREATE TABLE review_images (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id   bigint       NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
    public_id   varchar(255) NOT NULL,
    format      varchar(20)  NOT NULL,
    size_bytes  bigint       NOT NULL,
    sort_order  integer      NOT NULL,
    uploaded_at timestamp(6) NOT NULL
);
CREATE INDEX idx_review_images_review ON review_images (review_id, sort_order);
