-- =====================================================================
-- V17: Yêu cầu thiết kế tour riêng (khách gửi yêu cầu, Admin giao Agent, Agent nhận / từ chối)
--  - Trạng thái: NEW (chờ Admin giao) -> WAITING_AGENT (đã giao, Agent có 48 giờ để nhận)
--      -> IN_PROGRESS (Agent đã nhận, soạn đề xuất trong 72 giờ);
--    Agent từ chối / quá 48 giờ -> quay lại NEW để Admin giao người khác.
--    CANCELLED: khách hủy; CLOSED: Admin đóng hoặc hệ thống tự đóng (sát ngày đi mà chưa có Agent nhận).
--  - agent_id: Agent đang được giao / đang xử lý (đếm số yêu cầu đang mở của Agent).
--  - custom_request_assignments: lịch sử từng lần giao (không giao lại cho Agent đã từ chối / để hết hạn).
--  - Ngân sách tính theo VNĐ / người.
-- =====================================================================

CREATE TABLE custom_requests (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                  varchar(20)  NOT NULL,
    customer_id           bigint       NOT NULL REFERENCES users (id),
    departure_location_id bigint       NOT NULL REFERENCES locations (id),
    earliest_start        date         NOT NULL,
    latest_start          date         NOT NULL,
    duration_days         smallint     NOT NULL,
    adults                smallint     NOT NULL,
    children              smallint     NOT NULL,
    infants               smallint     NOT NULL,
    budget_min            bigint,
    budget_max            bigint,
    -- NULL = không yêu cầu
    accommodation_type    varchar(20),
    notes                 text,
    status                varchar(20)  NOT NULL,
    agent_id              bigint REFERENCES users (id),
    assigned_at           timestamp(6),
    accepted_at           timestamp(6),
    -- Hạn gửi đề xuất đầu tiên
    proposal_deadline     timestamp(6),
    closed_at             timestamp(6),
    closed_reason         text,
    version               bigint       NOT NULL DEFAULT 0,
    created_at            timestamp(6) NOT NULL,
    updated_at            timestamp(6),
    CONSTRAINT uq_custom_requests_code UNIQUE (code),
    CONSTRAINT custom_requests_status_check CHECK (status IN ('NEW', 'WAITING_AGENT', 'IN_PROGRESS', 'CANCELLED', 'CLOSED')),
    CONSTRAINT custom_requests_dates_check CHECK (latest_start >= earliest_start),
    CONSTRAINT custom_requests_counts_check CHECK (adults >= 1 AND children >= 0 AND infants >= 0 AND infants <= adults),
    CONSTRAINT custom_requests_budget_check CHECK (budget_min IS NULL OR budget_max IS NULL OR budget_min <= budget_max),
    CONSTRAINT custom_requests_accommodation_check CHECK (accommodation_type IN
        ('NONE', 'HOMESTAY', 'HOTEL_2_3_STAR', 'HOTEL_4_STAR', 'HOTEL_5_STAR', 'RESORT', 'CRUISE'))
);

CREATE INDEX idx_custom_requests_customer ON custom_requests (customer_id, created_at DESC);
CREATE INDEX idx_custom_requests_status ON custom_requests (status, created_at);
-- Đếm yêu cầu đang mở của Agent
CREATE INDEX idx_custom_requests_agent_open ON custom_requests (agent_id) WHERE status IN ('WAITING_AGENT', 'IN_PROGRESS');

CREATE TABLE custom_request_destinations (
    request_id  bigint NOT NULL REFERENCES custom_requests (id) ON DELETE CASCADE,
    location_id bigint NOT NULL REFERENCES locations (id),
    PRIMARY KEY (request_id, location_id)
);

CREATE TABLE custom_request_categories (
    request_id  bigint NOT NULL REFERENCES custom_requests (id) ON DELETE CASCADE,
    category_id bigint NOT NULL REFERENCES tour_categories (id),
    PRIMARY KEY (request_id, category_id)
);

CREATE TABLE custom_request_transport_modes (
    request_id bigint      NOT NULL REFERENCES custom_requests (id) ON DELETE CASCADE,
    mode       varchar(20) NOT NULL,
    PRIMARY KEY (request_id, mode),
    CONSTRAINT custom_request_transport_mode_check CHECK (mode IN ('BUS', 'PLANE', 'TRAIN', 'BOAT', 'MOTORBIKE', 'SELF_ARRANGED'))
);

CREATE TABLE custom_request_assignments (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     bigint       NOT NULL REFERENCES custom_requests (id) ON DELETE CASCADE,
    agent_id       bigint       NOT NULL REFERENCES users (id),
    assigned_by    bigint       NOT NULL REFERENCES users (id),
    status         varchar(20)  NOT NULL,
    -- Điểm phù hợp lúc giao (để xem lại vì sao chọn Agent này)
    match_score    numeric(5, 1),
    deadline       timestamp(6) NOT NULL,
    decline_reason text,
    responded_at   timestamp(6),
    created_at     timestamp(6) NOT NULL,
    CONSTRAINT custom_request_assignments_status_check CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'REVOKED'))
);

CREATE INDEX idx_cr_assignments_request ON custom_request_assignments (request_id, id);
CREATE INDEX idx_cr_assignments_agent ON custom_request_assignments (agent_id, created_at DESC);
-- Job hết hạn 48 giờ
CREATE INDEX idx_cr_assignments_pending ON custom_request_assignments (deadline) WHERE status = 'PENDING';
