-- =====================================================================
-- V18: Đề xuất lịch trình + báo giá cho yêu cầu thiết kế tour riêng
--  - Agent đã nhận gửi đề xuất (hạn 72 giờ bản đầu, 48 giờ mỗi bản chỉnh sửa — custom_requests.proposal_deadline).
--  - Khách có 3 ngày để Đồng ý hoặc Yêu cầu chỉnh sửa (tối đa 5 lần). Đồng ý -> yêu cầu AGREED (chốt, sang bước đặt cọc).
--  - Agent quá hạn gửi -> lần giao OVERDUE, yêu cầu quay lại chờ Admin giao đơn vị khác.
--  - Đang chờ khách mà không có trao đổi nào trong 5 ngày (last_activity_at) -> tự đóng.
--  - Mỗi lần gửi là một phiên bản mới (version_no đếm theo từng Agent), bản cũ giữ nguyên để đối chiếu.
-- =====================================================================

ALTER TABLE custom_requests DROP CONSTRAINT custom_requests_status_check;
ALTER TABLE custom_requests ADD CONSTRAINT custom_requests_status_check
    CHECK (status IN ('NEW', 'WAITING_AGENT', 'IN_PROGRESS', 'AGREED', 'CANCELLED', 'CLOSED'));

ALTER TABLE custom_requests
    -- Số lần khách đã yêu cầu chỉnh sửa (với Agent hiện tại)
    ADD COLUMN revision_count    smallint NOT NULL DEFAULT 0,
    -- Đã nhắc Agent sắp hết hạn gửi đề xuất (đặt lại mỗi lần có hạn mới)
    ADD COLUMN deadline_reminded boolean  NOT NULL DEFAULT false,
    ADD COLUMN last_activity_at  timestamp(6),
    ADD COLUMN agreed_at         timestamp(6);

UPDATE custom_requests SET last_activity_at = accepted_at WHERE status = 'IN_PROGRESS';

-- Job: Agent quá hạn / sắp hết hạn gửi đề xuất
CREATE INDEX idx_custom_requests_proposal_deadline ON custom_requests (proposal_deadline)
    WHERE status = 'IN_PROGRESS' AND proposal_deadline IS NOT NULL;
-- Job: đóng yêu cầu không có hoạt động
CREATE INDEX idx_custom_requests_activity ON custom_requests (last_activity_at)
    WHERE status = 'IN_PROGRESS' AND proposal_deadline IS NULL;

ALTER TABLE custom_request_assignments DROP CONSTRAINT custom_request_assignments_status_check;
ALTER TABLE custom_request_assignments ADD CONSTRAINT custom_request_assignments_status_check
    CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'REVOKED', 'OVERDUE'));

CREATE TABLE custom_proposals (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id         bigint       NOT NULL REFERENCES custom_requests (id) ON DELETE CASCADE,
    agent_id           bigint       NOT NULL REFERENCES users (id),
    version_no         smallint     NOT NULL,
    status             varchar(20)  NOT NULL,
    title              varchar(150) NOT NULL,
    start_date         date         NOT NULL,
    end_date           date         NOT NULL,
    duration_days      smallint     NOT NULL,
    duration_nights    smallint     NOT NULL,
    accommodation_type varchar(20)  NOT NULL,
    meeting_point      varchar(255) NOT NULL,
    meeting_time       time         NOT NULL,
    included_services  text[]       NOT NULL,
    excluded_services  text[]       NOT NULL DEFAULT '{}',
    notes              text,
    -- VNĐ / người; trẻ sơ sinh miễn phí
    adult_price        bigint       NOT NULL,
    child_price        bigint       NOT NULL,
    -- Tính lúc gửi theo số khách của yêu cầu
    total_price        bigint       NOT NULL,
    deposit_amount     bigint       NOT NULL,
    -- Lời nhắn của Agent cho phiên bản này
    agent_message      text,
    -- Khách yêu cầu chỉnh sửa gì
    customer_feedback  text,
    -- Hạn khách phản hồi
    expires_at         timestamp(6) NOT NULL,
    expiry_reminded    boolean      NOT NULL DEFAULT false,
    responded_at       timestamp(6),
    created_at         timestamp(6) NOT NULL,
    CONSTRAINT uq_custom_proposals_version UNIQUE (request_id, agent_id, version_no),
    CONSTRAINT custom_proposals_status_check CHECK (status IN
        ('SENT', 'ACCEPTED', 'REVISION_REQUESTED', 'DECLINED', 'EXPIRED', 'WITHDRAWN')),
    CONSTRAINT custom_proposals_dates_check CHECK (end_date >= start_date),
    CONSTRAINT custom_proposals_price_check CHECK (adult_price > 0 AND child_price >= 0 AND child_price <= adult_price),
    CONSTRAINT custom_proposals_accommodation_check CHECK (accommodation_type IN
        ('NONE', 'HOMESTAY', 'HOTEL_2_3_STAR', 'HOTEL_4_STAR', 'HOTEL_5_STAR', 'RESORT', 'CRUISE'))
);

CREATE INDEX idx_custom_proposals_request ON custom_proposals (request_id, id);
-- Mỗi yêu cầu chỉ có một đề xuất đang chờ khách
CREATE UNIQUE INDEX uq_custom_proposals_sent ON custom_proposals (request_id) WHERE status = 'SENT';
-- Job: đề xuất hết hạn / sắp hết hạn
CREATE INDEX idx_custom_proposals_expiry ON custom_proposals (expires_at) WHERE status = 'SENT';

CREATE TABLE custom_proposal_days (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id   bigint       NOT NULL REFERENCES custom_proposals (id) ON DELETE CASCADE,
    day_number    smallint     NOT NULL,
    title         varchar(200) NOT NULL,
    description   text         NOT NULL,
    has_breakfast boolean      NOT NULL,
    has_lunch     boolean      NOT NULL,
    has_dinner    boolean      NOT NULL,
    accommodation varchar(255),
    CONSTRAINT uq_custom_proposal_day UNIQUE (proposal_id, day_number)
);

CREATE TABLE custom_proposal_transport_modes (
    proposal_id bigint      NOT NULL REFERENCES custom_proposals (id) ON DELETE CASCADE,
    mode        varchar(20) NOT NULL,
    PRIMARY KEY (proposal_id, mode),
    CONSTRAINT custom_proposal_transport_mode_check CHECK (mode IN ('BUS', 'PLANE', 'TRAIN', 'BOAT', 'MOTORBIKE', 'SELF_ARRANGED'))
);
