-- =====================================================================
-- V19: Trao đổi giữa khách và đơn vị tổ chức trong yêu cầu thiết kế tour riêng
--  - Mỗi cuộc trò chuyện = (request_id, agent_id): yêu cầu giao lại cho đơn vị khác thì bắt đầu cuộc mới,
--    đơn vị cũ không xem được nữa, khách vẫn xem lại được.
--  - body lưu nguyên văn; số điện thoại / email được che khi trả cho khách và Agent (Admin xem bản gốc).
--  - chat_read_states: mỗi người nhớ đã đọc tới tin nào -> đếm chưa đọc, hiện "Đã xem".
-- =====================================================================

CREATE TABLE chat_messages (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id bigint       NOT NULL REFERENCES custom_requests (id) ON DELETE CASCADE,
    agent_id   bigint       NOT NULL REFERENCES users (id),
    sender_id  bigint       NOT NULL REFERENCES users (id),
    -- NULL khi tin chỉ có ảnh
    body       text,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT chat_messages_body_check CHECK (body IS NULL OR char_length(body) <= 2000)
);

CREATE INDEX idx_chat_messages_thread ON chat_messages (request_id, agent_id, id);

CREATE TABLE chat_message_images (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint       NOT NULL REFERENCES chat_messages (id) ON DELETE CASCADE,
    public_id  varchar(255) NOT NULL,
    format     varchar(20)  NOT NULL,
    size_bytes bigint       NOT NULL,
    sort_order smallint     NOT NULL
);

CREATE INDEX idx_chat_message_images_message ON chat_message_images (message_id);

CREATE TABLE chat_read_states (
    request_id           bigint       NOT NULL REFERENCES custom_requests (id) ON DELETE CASCADE,
    agent_id             bigint       NOT NULL REFERENCES users (id),
    user_id              bigint       NOT NULL REFERENCES users (id),
    last_read_message_id bigint       NOT NULL DEFAULT 0,
    updated_at           timestamp(6) NOT NULL,
    PRIMARY KEY (request_id, agent_id, user_id)
);
