-- =====================================================================
-- V1: Cấu trúc DB tại thời điểm chuyển sang Flyway (trích từ DB thật bằng pg_dump --schema-only).
-- DB đã có sẵn bảng sẽ được baseline ở version 1 (file này bị bỏ qua);
-- DB mới tinh sẽ chạy file này để tạo toàn bộ bảng.
-- Tên constraint giữ nguyên như Hibernate đã sinh để mọi DB giống hệt nhau.
-- KHÔNG sửa file này sau khi đã chạy — muốn thay đổi thì tạo migration mới.
-- =====================================================================

CREATE TABLE users (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at            timestamp(6),
    email                 varchar(255) NOT NULL,
    email_verified        boolean      NOT NULL,
    failed_login_attempts integer      NOT NULL,
    full_name             varchar(255),
    last_login_at         timestamp(6),
    locked_until          timestamp(6),
    otp_expires_at        timestamp(6),
    password_hash         varchar(255),
    phone                 varchar(255),
    role                  varchar(255) NOT NULL,
    google_id             varchar(255),
    otp_attempts          integer      NOT NULL DEFAULT 0,
    otp_hash              varchar(64),
    otp_purpose           varchar(20),
    otp_sent_at           timestamp(6),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT ukovh8xmu9ac27t18m56gri58i1 UNIQUE (google_id),
    CONSTRAINT users_role_check CHECK (role IN ('CUSTOMER', 'AGENT', 'ADMIN')),
    CONSTRAINT users_otp_purpose_check CHECK (otp_purpose IN ('REGISTER', 'UNLOCK', 'RESET_PASSWORD'))
);

CREATE TABLE refresh_tokens (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6),
    expires_at timestamp(6) NOT NULL,
    revoked    boolean      NOT NULL,
    token      varchar(200) NOT NULL,
    user_id    bigint       NOT NULL,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token),
    CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE agent_profiles (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY,
    bank_account          varchar(255),
    business_license      varchar(255),
    company_name          varchar(255),
    created_at            timestamp(6),
    is_accepting_requests boolean      NOT NULL,
    max_open_requests     integer      NOT NULL,
    rating                numeric(38, 2),
    rejection_reason      text,
    status                varchar(255) NOT NULL,
    tax_code              varchar(255),
    user_id               bigint       NOT NULL,
    CONSTRAINT agent_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT ukryi1mro1uwvyr3aotwximyphp UNIQUE (user_id),
    CONSTRAINT fko3kghcnui01ek5p6ymolvgmoc FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT agent_profiles_status_check CHECK (status IN ('PENDING_APPROVAL', 'NEEDS_REVISION', 'APPROVED'))
);

CREATE TABLE locations (
    id       bigint GENERATED BY DEFAULT AS IDENTITY,
    country  varchar(255) NOT NULL,
    province varchar(255),
    CONSTRAINT locations_pkey PRIMARY KEY (id)
);

CREATE TABLE tour_categories (
    id   bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    CONSTRAINT tour_categories_pkey PRIMARY KEY (id),
    CONSTRAINT ukjfsjq584lr1fqs553dspy8ib8 UNIQUE (name)
);

CREATE TABLE agent_service_areas (
    agent_id    bigint NOT NULL,
    location_id bigint NOT NULL,
    CONSTRAINT agent_service_areas_pkey PRIMARY KEY (agent_id, location_id),
    CONSTRAINT fks959lts1pgvvmoebbwopnjbrw FOREIGN KEY (agent_id) REFERENCES users (id),
    CONSTRAINT fkolxi37ck500awqyjb7huo21ua FOREIGN KEY (location_id) REFERENCES locations (id)
);

CREATE TABLE agent_specialties (
    agent_id    bigint NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT agent_specialties_pkey PRIMARY KEY (agent_id, category_id),
    CONSTRAINT fkq289d9r2rqrwx1snlii6d5mr9 FOREIGN KEY (agent_id) REFERENCES users (id),
    CONSTRAINT fk2ixefunew77g7uwq64hj6358 FOREIGN KEY (category_id) REFERENCES tour_categories (id)
);
