-- =====================================================================
-- V21: Đối soát hoa hồng với đơn vị tổ chức
--  - Ngày 1 hằng tháng (hoặc Admin lập ngay): mỗi Agent một bảng đối soát gồm các đơn CHƯA đối soát
--    đã hoàn thành / bị hủy mà TripConnect vẫn giữ tiền, phát sinh trước thời điểm chốt (cutoff_at).
--  - Dòng đối soát: tiền giữ lại = đã thu - đã hoàn; hoa hồng theo tỷ lệ chụp trong đơn; Agent nhận phần còn lại.
--  - Trạng thái: PENDING_CONFIRM (Agent xem, 5 ngày) -> DISPUTED (Agent khiếu nại, chờ Admin)
--      -> PENDING_CONFIRM lại (Admin điều chỉnh) / AWAITING_PAYMENT (xác nhận / bác khiếu nại / quá hạn tự xác nhận)
--      -> PAID (Admin chuyển khoản, ghi mã giao dịch).
--  - Tài khoản nhận tiền chụp lại lúc Admin trả.
-- =====================================================================

CREATE TABLE settlements (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                varchar(20)  NOT NULL,
    agent_id            bigint       NOT NULL REFERENCES users (id),
    -- Gồm các đơn phát sinh trước thời điểm này
    cutoff_at           timestamp(6) NOT NULL,
    status              varchar(20)  NOT NULL,
    item_count          integer      NOT NULL,
    retained_amount     bigint       NOT NULL,
    commission_amount   bigint       NOT NULL,
    adjustment_amount   bigint       NOT NULL DEFAULT 0,
    payout_amount       bigint       NOT NULL,
    confirm_deadline    timestamp(6),
    confirmed_at        timestamp(6),
    auto_confirmed      boolean      NOT NULL DEFAULT false,
    paid_at             timestamp(6),
    paid_by             bigint REFERENCES users (id),
    bank_bin            varchar(6),
    bank_name           varchar(255),
    bank_account_number varchar(19),
    bank_account_holder varchar(255),
    transaction_ref     varchar(100),
    receipt_public_id   varchar(255),
    receipt_format      varchar(20),
    version             bigint       NOT NULL DEFAULT 0,
    created_at          timestamp(6) NOT NULL,
    updated_at          timestamp(6),
    CONSTRAINT uq_settlements_code UNIQUE (code),
    CONSTRAINT settlements_status_check CHECK (status IN ('PENDING_CONFIRM', 'DISPUTED', 'AWAITING_PAYMENT', 'PAID'))
);

CREATE INDEX idx_settlements_agent ON settlements (agent_id, id DESC);
CREATE INDEX idx_settlements_status ON settlements (status, id);
-- Job tự xác nhận khi quá hạn
CREATE INDEX idx_settlements_confirm_deadline ON settlements (confirm_deadline) WHERE status = 'PENDING_CONFIRM';

CREATE TABLE settlement_items (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id     bigint        NOT NULL REFERENCES settlements (id) ON DELETE CASCADE,
    booking_id        bigint        NOT NULL REFERENCES bookings (id),
    -- COMPLETED: đơn hoàn thành; CANCELLED: đơn hủy mà vẫn giữ tiền (khách hủy sát ngày, mất cọc)
    kind              varchar(20)   NOT NULL,
    event_at          timestamp(6)  NOT NULL,
    paid_amount       bigint        NOT NULL,
    refunded_amount   bigint        NOT NULL,
    retained_amount   bigint        NOT NULL,
    commission_rate   numeric(5, 4) NOT NULL,
    commission_amount bigint        NOT NULL,
    payout_amount     bigint        NOT NULL,
    -- Mỗi đơn chỉ được đối soát một lần
    CONSTRAINT uq_settlement_items_booking UNIQUE (booking_id),
    CONSTRAINT settlement_items_kind_check CHECK (kind IN ('COMPLETED', 'CANCELLED'))
);

CREATE INDEX idx_settlement_items_settlement ON settlement_items (settlement_id, event_at);

CREATE TABLE settlement_adjustments (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id bigint       NOT NULL REFERENCES settlements (id) ON DELETE CASCADE,
    -- Dương: cộng thêm cho Agent; âm: trừ bớt
    amount        bigint       NOT NULL,
    reason        text         NOT NULL,
    created_by    bigint       NOT NULL REFERENCES users (id),
    created_at    timestamp(6) NOT NULL,
    CONSTRAINT settlement_adjustments_amount_check CHECK (amount <> 0)
);

CREATE TABLE settlement_disputes (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id bigint       NOT NULL REFERENCES settlements (id) ON DELETE CASCADE,
    reason        text         NOT NULL,
    -- OPEN chờ xử lý; ADJUSTED đã điều chỉnh, gửi Agent xác nhận lại; REJECTED bác khiếu nại
    status        varchar(20)  NOT NULL,
    resolution    text,
    resolved_by   bigint REFERENCES users (id),
    resolved_at   timestamp(6),
    created_at    timestamp(6) NOT NULL,
    CONSTRAINT settlement_disputes_status_check CHECK (status IN ('OPEN', 'ADJUSTED', 'REJECTED'))
);

CREATE INDEX idx_settlement_disputes_settlement ON settlement_disputes (settlement_id, id);
