-- =====================================================================
-- V22: Trợ lý AI và gợi ý tour
--  - tour_embeddings / knowledge_chunks: véc-tơ (embedding) cho tìm kiếm theo ý nghĩa (RAG). Lưu dạng real[] trong
--    PostgreSQL sẵn có, độ giống tính trong backend (vài trăm tour không cần extension riêng).
--    content_hash: nội dung đổi / đổi model thì tạo lại véc-tơ.
--  - tour_views: lượt xem trang tour (người đăng nhập hoặc mã khách vãng lai) — dữ liệu cho gợi ý cá nhân hóa.
--  - ai_conversations / ai_messages: lịch sử trò chuyện với trợ lý của người đã đăng nhập.
-- =====================================================================

CREATE TABLE tour_embeddings (
    tour_id      bigint       PRIMARY KEY REFERENCES tours (id) ON DELETE CASCADE,
    model        varchar(60)  NOT NULL,
    content_hash varchar(64)  NOT NULL,
    vector       real[]       NOT NULL,
    updated_at   timestamp(6) NOT NULL
);

CREATE TABLE knowledge_chunks (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Tên file trong resources/knowledge, vd huy-tour.md
    source       varchar(100) NOT NULL,
    title        varchar(255) NOT NULL,
    content      text         NOT NULL,
    model        varchar(60)  NOT NULL,
    content_hash varchar(64)  NOT NULL,
    vector       real[]       NOT NULL,
    updated_at   timestamp(6) NOT NULL,
    CONSTRAINT uq_knowledge_chunks UNIQUE (source, title)
);

CREATE TABLE tour_views (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id    bigint       NOT NULL REFERENCES tours (id) ON DELETE CASCADE,
    user_id    bigint REFERENCES users (id) ON DELETE CASCADE,
    visitor_id varchar(64),
    viewed_at  timestamp(6) NOT NULL,
    CONSTRAINT tour_views_viewer_check CHECK (user_id IS NOT NULL OR visitor_id IS NOT NULL)
);

CREATE INDEX idx_tour_views_user ON tour_views (user_id, viewed_at DESC) WHERE user_id IS NOT NULL;
CREATE INDEX idx_tour_views_visitor ON tour_views (visitor_id, viewed_at DESC) WHERE visitor_id IS NOT NULL;
CREATE INDEX idx_tour_views_tour ON tour_views (tour_id, viewed_at DESC);

CREATE TABLE ai_conversations (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title      varchar(120) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);

CREATE INDEX idx_ai_conversations_user ON ai_conversations (user_id, updated_at DESC);

CREATE TABLE ai_messages (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint       NOT NULL REFERENCES ai_conversations (id) ON DELETE CASCADE,
    -- USER / ASSISTANT
    role            varchar(20)  NOT NULL,
    content         text         NOT NULL,
    -- Phần đính kèm hiển thị (thẻ tour, gợi ý gửi yêu cầu tour riêng...) dạng JSON
    attachments     text,
    created_at      timestamp(6) NOT NULL,
    CONSTRAINT ai_messages_role_check CHECK (role IN ('USER', 'ASSISTANT'))
);

CREATE INDEX idx_ai_messages_conversation ON ai_messages (conversation_id, id);
