-- =====================================================================
-- V3: Hoàn thiện hồ sơ Agent
--  - Thêm địa chỉ, mốc nộp/duyệt, người duyệt, số lượt đánh giá
--  - Trạng thái mới DRAFT: hồ sơ chưa nộp (Agent upload giấy tờ sau khi xác thực email)
--  - "Đang nhận yêu cầu" chỉ bật khi hồ sơ đã được duyệt
--  - Giấy tờ pháp lý (file private trên Cloudinary)
--  - Yêu cầu cập nhật hồ sơ sau khi đã duyệt (Admin duyệt thì mới áp dụng)
-- =====================================================================

-- ----- agent_profiles -----
ALTER TABLE agent_profiles ADD COLUMN address      varchar(500);
ALTER TABLE agent_profiles ADD COLUMN submitted_at timestamp(6);
ALTER TABLE agent_profiles ADD COLUMN reviewed_at  timestamp(6);
ALTER TABLE agent_profiles ADD COLUMN reviewed_by  bigint REFERENCES users (id);
ALTER TABLE agent_profiles ADD COLUMN rating_count integer NOT NULL DEFAULT 0;
ALTER TABLE agent_profiles ADD COLUMN updated_at   timestamp(6);

-- Điểm đánh giá trung bình 1.00 - 5.00
ALTER TABLE agent_profiles ALTER COLUMN rating TYPE numeric(3, 2);

ALTER TABLE agent_profiles ALTER COLUMN is_accepting_requests SET DEFAULT false;
UPDATE agent_profiles SET is_accepting_requests = false WHERE status <> 'APPROVED';

ALTER TABLE agent_profiles DROP CONSTRAINT agent_profiles_status_check;
ALTER TABLE agent_profiles ADD CONSTRAINT agent_profiles_status_check
    CHECK (status IN ('DRAFT', 'PENDING_APPROVAL', 'NEEDS_REVISION', 'APPROVED'));

CREATE INDEX idx_agent_profiles_status ON agent_profiles (status);

-- ----- Yêu cầu cập nhật hồ sơ (sau khi đã duyệt) -----
-- Cột thông tin = NULL nghĩa là "không đổi trường này"
CREATE TABLE agent_profile_change_requests (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_profile_id bigint       NOT NULL REFERENCES agent_profiles (id),
    company_name     varchar(255),
    tax_code         varchar(255),
    business_license varchar(255),
    address          varchar(500),
    bank_account     varchar(255),
    status           varchar(20)  NOT NULL,
    rejection_reason text,
    reviewed_by      bigint REFERENCES users (id),
    reviewed_at      timestamp(6),
    created_at       timestamp(6) NOT NULL,
    CONSTRAINT agent_profile_change_requests_status_check
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

-- Mỗi Agent chỉ có tối đa 1 yêu cầu đang chờ duyệt (DB tự chặn, kể cả khi 2 request gửi cùng lúc)
CREATE UNIQUE INDEX uq_agent_change_request_one_pending
    ON agent_profile_change_requests (agent_profile_id) WHERE status = 'PENDING';
CREATE INDEX idx_agent_change_requests_status ON agent_profile_change_requests (status, created_at);

-- ----- Giấy tờ pháp lý -----
-- status: ACTIVE = đang dùng; PENDING = nằm trong yêu cầu cập nhật chờ duyệt; ARCHIVED = đã bị thay thế (giữ lại để tra cứu)
CREATE TABLE agent_documents (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_profile_id  bigint       NOT NULL REFERENCES agent_profiles (id),
    change_request_id bigint REFERENCES agent_profile_change_requests (id),
    type              varchar(40)  NOT NULL,
    status            varchar(20)  NOT NULL,
    public_id         varchar(255) NOT NULL,
    format            varchar(20)  NOT NULL,
    mime_type         varchar(100) NOT NULL,
    size_bytes        bigint       NOT NULL,
    original_filename varchar(255),
    uploaded_at       timestamp(6) NOT NULL,
    CONSTRAINT agent_documents_type_check CHECK (type IN
        ('TRAVEL_LICENSE', 'BUSINESS_REGISTRATION', 'REPRESENTATIVE_ID_FRONT', 'REPRESENTATIVE_ID_BACK', 'OTHER')),
    CONSTRAINT agent_documents_status_check CHECK (status IN ('ACTIVE', 'PENDING', 'ARCHIVED'))
);

CREATE INDEX idx_agent_documents_profile ON agent_documents (agent_profile_id, status);
CREATE INDEX idx_agent_documents_change_request ON agent_documents (change_request_id);
