-- =====================================================================
-- V7: Tour đoàn công khai + lịch khởi hành
--  - Tour do Agent tạo phải được Admin duyệt; tour do Admin tạo (agent_id NULL = TripConnect tự tổ chức) công khai ngay
--  - Danh sách chỉ để hiển thị (điểm nổi bật, bao gồm, không bao gồm) lưu kiểu mảng text[]
--  - Dữ liệu cần lọc/tìm kiếm (loại hình, điểm đến, phương tiện) lưu bảng nối riêng
--  - Giá tính bằng VNĐ (số nguyên), đặt theo TỪNG lịch khởi hành
-- =====================================================================

CREATE TABLE tours (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Agent tổ chức tour (users.id, giống agent_service_areas); NULL = tour của TripConnect do Admin tạo
    agent_id               bigint REFERENCES users (id),
    created_by             bigint       NOT NULL REFERENCES users (id),
    title                  varchar(150) NOT NULL,
    departure_location_id  bigint       NOT NULL REFERENCES locations (id),
    duration_days          smallint     NOT NULL,
    duration_nights        smallint     NOT NULL,
    -- Tự tính: có ít nhất 1 điểm đến ngoài Việt Nam
    is_international       boolean      NOT NULL DEFAULT false,
    highlights             text[]       NOT NULL,
    included_services      text[]       NOT NULL,
    excluded_services      text[]       NOT NULL DEFAULT '{}',
    notes                  text,
    accommodation_type     varchar(20)  NOT NULL,
    meeting_point          varchar(255) NOT NULL,
    meeting_time           time         NOT NULL,
    -- File chương trình tour (PDF, không bắt buộc) — lưu private, xem qua link tạm thời
    itinerary_file_public_id varchar(255),
    itinerary_file_format    varchar(20),
    itinerary_file_size      bigint,
    itinerary_file_name      varchar(255),
    status                 varchar(20)  NOT NULL,
    -- Lý do Admin yêu cầu chỉnh sửa / đình chỉ
    status_reason          text,
    submitted_at           timestamp(6),
    reviewed_at            timestamp(6),
    reviewed_by            bigint REFERENCES users (id),
    -- Lần đầu được công khai (khác NULL = tour đã từng bán -> lần duyệt sau là "duyệt lại nội dung")
    published_at           timestamp(6),
    rating                 numeric(3, 2),
    rating_count           integer      NOT NULL DEFAULT 0,
    version                bigint       NOT NULL DEFAULT 0,
    created_at             timestamp(6) NOT NULL,
    updated_at             timestamp(6),
    CONSTRAINT tours_status_check CHECK (status IN
        ('DRAFT', 'PENDING_APPROVAL', 'NEEDS_REVISION', 'PUBLISHED', 'HIDDEN', 'SUSPENDED')),
    CONSTRAINT tours_accommodation_check CHECK (accommodation_type IN
        ('NONE', 'HOMESTAY', 'HOTEL_2_3_STAR', 'HOTEL_4_STAR', 'HOTEL_5_STAR', 'RESORT', 'CRUISE')),
    CONSTRAINT tours_duration_check CHECK (duration_days BETWEEN 1 AND 30
        AND duration_nights BETWEEN duration_days - 1 AND duration_days)
);

CREATE INDEX idx_tours_agent ON tours (agent_id, status);
CREATE INDEX idx_tours_status ON tours (status, submitted_at);

CREATE TABLE tour_category_links (
    tour_id     bigint NOT NULL REFERENCES tours (id) ON DELETE CASCADE,
    category_id bigint NOT NULL REFERENCES tour_categories (id),
    PRIMARY KEY (tour_id, category_id)
);
CREATE INDEX idx_tour_category_links_category ON tour_category_links (category_id);

CREATE TABLE tour_destinations (
    tour_id     bigint NOT NULL REFERENCES tours (id) ON DELETE CASCADE,
    location_id bigint NOT NULL REFERENCES locations (id),
    PRIMARY KEY (tour_id, location_id)
);
CREATE INDEX idx_tour_destinations_location ON tour_destinations (location_id);

CREATE TABLE tour_transport_modes (
    tour_id bigint      NOT NULL REFERENCES tours (id) ON DELETE CASCADE,
    mode    varchar(20) NOT NULL,
    PRIMARY KEY (tour_id, mode),
    CONSTRAINT tour_transport_modes_mode_check CHECK (mode IN
        ('BUS', 'PLANE', 'TRAIN', 'BOAT', 'MOTORBIKE', 'SELF_ARRANGED'))
);

-- Lịch trình từng ngày
CREATE TABLE tour_itinerary_days (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id       bigint       NOT NULL REFERENCES tours (id) ON DELETE CASCADE,
    day_number    smallint     NOT NULL,
    title         varchar(200) NOT NULL,
    description   text         NOT NULL,
    has_breakfast boolean      NOT NULL DEFAULT false,
    has_lunch     boolean      NOT NULL DEFAULT false,
    has_dinner    boolean      NOT NULL DEFAULT false,
    accommodation varchar(255),
    CONSTRAINT uq_tour_itinerary_day UNIQUE (tour_id, day_number)
);

-- Ảnh tour (public). Ảnh có sort_order nhỏ nhất là ảnh bìa.
CREATE TABLE tour_images (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id     bigint       NOT NULL REFERENCES tours (id) ON DELETE CASCADE,
    public_id   varchar(255) NOT NULL,
    format      varchar(20)  NOT NULL,
    size_bytes  bigint       NOT NULL,
    sort_order  integer      NOT NULL,
    uploaded_at timestamp(6) NOT NULL
);
CREATE INDEX idx_tour_images_tour ON tour_images (tour_id, sort_order);

-- Lịch khởi hành. Ngày về = start_date + duration_days - 1 (không lưu để không bị lệch khi đổi số ngày).
CREATE TABLE tour_departures (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id       bigint       NOT NULL REFERENCES tours (id) ON DELETE CASCADE,
    start_date    date         NOT NULL,
    capacity      integer      NOT NULL,
    adult_price   bigint       NOT NULL,
    child_price   bigint       NOT NULL,
    status        varchar(20)  NOT NULL,
    cancel_reason text,
    created_at    timestamp(6) NOT NULL,
    updated_at    timestamp(6),
    CONSTRAINT tour_departures_status_check CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED')),
    CONSTRAINT tour_departures_capacity_check CHECK (capacity BETWEEN 1 AND 100),
    CONSTRAINT tour_departures_price_check CHECK (adult_price > 0 AND child_price >= 0 AND child_price <= adult_price)
);

-- Một tour không có 2 lịch (chưa hủy) trùng ngày khởi hành
CREATE UNIQUE INDEX uq_tour_departure_date ON tour_departures (tour_id, start_date) WHERE status <> 'CANCELLED';
CREATE INDEX idx_tour_departures_start ON tour_departures (start_date, status);
