-- =====================================================================
-- V9: Tìm kiếm tour + lịch sử tìm kiếm
--  - tours.search_text: chữ thường KHÔNG DẤU của tên tour, điểm đến, loại hình, điểm nổi bật
--    (Java tạo sẵn khi lưu tour) -> gõ "ha long" vẫn tìm ra "Hạ Long", không cần tiện ích unaccent của PostgreSQL.
--    Tour đã có từ trước được điền khi backend khởi động (TourSearchTextBackfill).
--  - search_logs: lịch sử tìm kiếm của người đăng nhập (user_id) và khách (visitor_id = mã ngẫu nhiên
--    lưu ở trình duyệt, không chứa thông tin cá nhân). Dùng cho "Tìm kiếm gần đây" và gợi ý tour (bước 8).
--    Tự xóa sau 180 ngày (SearchLogCleanupJob).
-- =====================================================================

ALTER TABLE tours ADD COLUMN search_text text NOT NULL DEFAULT '';

-- Lọc tour đang bán theo thời lượng / nơi khởi hành nhanh hơn
CREATE INDEX idx_tours_published ON tours (status, duration_days) WHERE status = 'PUBLISHED';
CREATE INDEX idx_tours_departure_location ON tours (departure_location_id);
-- Tìm lịch còn mở bán của một tour theo ngày / giá
CREATE INDEX idx_tour_departures_open ON tour_departures (tour_id, start_date, adult_price) WHERE status = 'OPEN';

CREATE TABLE search_logs (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               bigint REFERENCES users (id) ON DELETE CASCADE,
    visitor_id            varchar(36),
    keyword               varchar(200),
    destination_id        bigint REFERENCES locations (id),
    departure_location_id bigint REFERENCES locations (id),
    date_from             date,
    date_to               date,
    price_min             bigint,
    price_max             bigint,
    duration_min          smallint,
    duration_max          smallint,
    category_ids          bigint[]     NOT NULL DEFAULT '{}',
    international         boolean,
    result_count          integer      NOT NULL,
    created_at            timestamp(6) NOT NULL,
    CONSTRAINT search_logs_owner_check CHECK (user_id IS NOT NULL OR visitor_id IS NOT NULL)
);

CREATE INDEX idx_search_logs_user ON search_logs (user_id, created_at DESC);
CREATE INDEX idx_search_logs_visitor ON search_logs (visitor_id, created_at DESC) WHERE user_id IS NULL;
CREATE INDEX idx_search_logs_created ON search_logs (created_at);
