package com.tripconnect.backend.enums;

/** Loại thông báo trên web — Frontend dựa vào đây để chọn biểu tượng. */
public enum NotificationType {
    // Khách
    BOOKING_PAID,
    BOOKING_CANCELLED,
    BOOKING_DEPOSIT_PAID,
    BOOKING_PAYMENT_DUE,
    REFUND_COMPLETED,
    TRIP_REMINDER,
    REVIEW_INVITE,
    REVIEW_REPLIED,
    REVIEW_HIDDEN,
    REVIEW_UNHIDDEN,
    CUSTOM_REQUEST_ACCEPTED,
    CUSTOM_REQUEST_CLOSED,
    CUSTOM_REQUEST_REASSIGNING,
    CUSTOM_PROPOSAL_RECEIVED,
    CUSTOM_PROPOSAL_EXPIRING,
    CUSTOM_PROPOSAL_EXPIRED,
    // Agent
    NEW_BOOKING,
    BOOKING_BALANCE_EXTENDED,
    TOUR_APPROVED,
    TOUR_NEEDS_REVISION,
    TOUR_SUSPENDED,
    TOUR_UNSUSPENDED,
    AGENT_PROFILE_APPROVED,
    AGENT_PROFILE_NEEDS_REVISION,
    CHANGE_REQUEST_APPROVED,
    CHANGE_REQUEST_REJECTED,
    CUSTOM_REQUEST_ASSIGNED,
    CUSTOM_REQUEST_EXPIRED,
    CUSTOM_REQUEST_CANCELLED,
    CUSTOM_PROPOSAL_REVISION_REQUESTED,
    CUSTOM_PROPOSAL_ACCEPTED,
    CUSTOM_PROPOSAL_DUE_SOON,
    CUSTOM_PROPOSAL_OVERDUE,
    // Khách và Agent
    CHAT_MESSAGE,
    // Đơn vị tổ chức (Agent, hoặc Admin với tour của TripConnect)
    NEW_REVIEW,
    TOUR_REVIEW_HIDDEN,
    TOUR_REVIEW_UNHIDDEN,
    DEPARTURE_REMINDER,
    LOW_BOOKINGS,
    // Admin
    AGENT_PROFILE_SUBMITTED,
    CHANGE_REQUEST_SUBMITTED,
    TOUR_SUBMITTED,
    MANUAL_REFUND_NEEDED,
    CUSTOM_REQUEST_NEW,
    CUSTOM_REQUEST_DECLINED
}
